# Generated by Django 6.0.6 on 2026-07-02 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_advertisement_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisementImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.advertisement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
