# Generated by Django 6.0.6 on 2026-07-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_advertisementimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
