# Generated by Django 6.0.6 on 2026-07-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_advertisement_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
