# Generated by Django 6.0.6 on 2026-07-02 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_advertisement_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisementimage",
            name="advertisement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="main.advertisement",
            ),
        ),
    ]
