# Generated by Django 6.0.6 on 2026-07-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_advertisementimage_advertisement"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.DeleteModel(
            name="AdvertisementImage",
        ),
    ]
