# Generated by Django 6.0.6 on 2026-07-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_savedad_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advertisement",
            old_name="image",
            new_name="image_1",
        ),
        migrations.AddField(
            model_name="advertisement",
            name="image_2",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="image_3",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="image_4",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="image_5",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="image_6",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="image_7",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="image_8",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
