# Generated by Django 6.0.6 on 2026-07-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_savedad_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advertisement",
            old_name="image_1",
            new_name="images",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="image_2",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="image_3",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="image_4",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="image_5",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="image_6",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="image_7",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="image_8",
        ),
    ]
