# Generated by Django 6.0.6 on 2026-07-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_subcategory_advertisement_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
