# Generated by Django 6.0.6 on 2026-07-14 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_subcategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("archived", "Archived"),
                    ("waiting", "Waiting"),
                    ("rejected", "Rejected"),
                ],
                default="waiting",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="main.category",
            ),
        ),
    ]
