# Generated by Django 6.0.6 on 2026-07-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_subcategory_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisement",
            name="subcategory",
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="main.category",
            ),
        ),
        migrations.DeleteModel(
            name="SubCategory",
        ),
    ]
